version: '1.2'
services: 
  j_frontend:
    build: frontend/
    container_name: frontend
    command: npm start
    networks: 
      - back
    ports: 
      - '3000:3000'
    depends_on:
      - j_backend
    tty: true
  
  j_backend:
    build: backend/
    restart: always
    container_name: backend
    networks: 
      - back
    command: npm start
    ports:
      - '3001:3001'

  python_api:
    build: pythonApi/
    restart: always
    container_name: pythonApi
    volumes: 
      - ./pythonApi:/lycoris/pythonApi
    command: flask --app app run --host 0.0.0.0 -p 3002
    networks:
      - back
    ports:
      - '3002:3002'

networks:
  back:
    driver: bridge